baseURL = 'https://francoispetitit.com'
languageCode = 'fr-fr'
title = 'François Petitit'
pagination.paperSize = 10
theme = 'DoIt'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "François Petitit"
  [params.author]
    name = 'François Petitit'

  [params.comments]
    enabled = true
    githubRepo = 'fpetitit/blog'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[params.home.profile]
  enable = true
  # Gravatar Email for preferred avatar in home page
  gravatarEmail = "francois.petitit@gmail.com"
  # URL of avatar shown in home page
  avatarURL = "/images/avatar.webp"
  # URL the avatar links to
  avatarLinkURL = ""


ignoreErrors = ["error-remote-getjson"]